"""Scaffolds a replay/testdata/<slug>_window/ fixture for a new sport, mapping
a plain-English sport name to The Odds API's sport-key convention and ESPN's
site-API sport/league path convention -- the same two env-var shapes
feed/odds_poller.py (ODDS_SPORT) and feed/scores_poller.py (SCORES_SPORT/
SCORES_LEAGUE) already use.

Only covers sports whose keys are already confirmed working in this repo
(NBA) or are well-established public conventions (NFL, MLB, NHL, WNBA).
Anything else: verify both identifiers yourself before trusting the printed
commands -- see SKILL.md's "only major sports are pre-verified" note.

Usage: python3 skills/scaffold-new-market/scripts/scaffold_market.py <sport-name>
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
TESTDATA_DIR = REPO_ROOT / "replay" / "testdata"

# name/alias -> (display_name, odds_api_sport_key, espn_sport, espn_league, slug)
SPORTS: dict[str, tuple[str, str, str, str, str]] = {
    "nba": ("NBA", "basketball_nba", "basketball", "nba", "nba"),
    "basketball": ("NBA", "basketball_nba", "basketball", "nba", "nba"),
    "wnba": ("WNBA", "basketball_wnba", "basketball", "wnba", "wnba"),
    "nfl": ("NFL", "americanfootball_nfl", "football", "nfl", "nfl"),
    "football": ("NFL", "americanfootball_nfl", "football", "nfl", "nfl"),
    "nhl": ("NHL", "icehockey_nhl", "hockey", "nhl", "nhl"),
    "hockey": ("NHL", "icehockey_nhl", "hockey", "nhl", "nhl"),
    "mlb": ("MLB", "baseball_mlb", "baseball", "mlb", "mlb"),
    "baseball": ("MLB", "baseball_mlb", "baseball", "mlb", "mlb"),
}


def scaffold(sport_key: str) -> int:
    entry = SPORTS.get(sport_key.strip().lower())
    if entry is None:
        print(f"[scaffold-new-market] unknown sport '{sport_key}'. Known: {', '.join(sorted(set(v[0] for v in SPORTS.values())))}", file=sys.stderr)
        print("[scaffold-new-market] verify the Odds-API/ESPN keys yourself for anything else -- see SKILL.md", file=sys.stderr)
        return 1

    display_name, odds_sport, espn_sport, espn_league, slug = entry
    window_dir = TESTDATA_DIR / f"{slug}_window"
    if window_dir.exists():
        print(f"[scaffold-new-market] {window_dir.relative_to(REPO_ROOT)} already exists -- not overwriting", file=sys.stderr)
        return 1
    window_dir.mkdir(parents=True)

    now = datetime.now(timezone.utc).isoformat()

    readme = f"""# Fixture capture window ({display_name})

**Placeholder fixture, not a live capture.** Generated by
`skills/scaffold-new-market` to get the schema shape right; both rows below
are made up and must be replaced with real data before this window is
trusted for anything.

Odds-API sport key: `{odds_sport}`
ESPN sport/league path: `{espn_sport}/{espn_league}`

## Replace before real use

1. Run a live capture (commands printed by the scaffolding script, or see
   `CLAUDE.md`'s Build/test commands section) to populate real rows.
2. Overwrite `odds.ndjson` / `scores.ndjson` in this directory with the real
   captured rows.
3. Update this README to say "real capture" instead of "placeholder
   fixture," same as `replay/testdata/sample_window/README.md` does.
"""
    (window_dir / "README.md").write_text(readme)

    odds_row = {
        "captured_at": now,
        "market_id": "PLACEHOLDER_EVENT_ID",
        "event_id": "PLACEHOLDER_EVENT_ID",
        "commence_time": now,
        "home_team": "Placeholder Home",
        "away_team": "Placeholder Away",
        "bookmaker": "placeholder_book",
        "outcome_name": "Placeholder Home",
        "price_american": -110,
        "last_update": now,
    }
    scores_row = {
        "captured_at": now,
        "event_id": "PLACEHOLDER_EVENT_ID",
        "home_team": "Placeholder Home",
        "away_team": "Placeholder Away",
        "home_score": 0,
        "away_score": 0,
        "status": "scheduled",
        "winner": None,
    }
    (window_dir / "odds.ndjson").write_text(json.dumps(odds_row) + "\n")
    (window_dir / "scores.ndjson").write_text(json.dumps(scores_row) + "\n")

    rel = window_dir.relative_to(REPO_ROOT)
    print(f"[scaffold-new-market] created {rel}/ (README.md, odds.ndjson, scores.ndjson -- placeholder rows)")
    print()
    print("Next: capture real data for this sport --")
    print(f"  ODDS_SPORT={odds_sport} ODDS_API_KEY=<your key> python3 feed/odds_poller.py")
    print(f"  SCORES_SPORT={espn_sport} SCORES_LEAGUE={espn_league} python3 feed/scores_poller.py")
    print()
    print("Then replace this window's placeholder rows with the real captured ones, and replay it:")
    print(f"  python3 replay/diff_gate.py --odds {rel}/odds.ndjson --scores {rel}/scores.ndjson")
    return 0


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: python3 {Path(sys.argv[0]).name} <sport-name>", file=sys.stderr)
        print(f"Known sports: {', '.join(sorted(set(v[0] for v in SPORTS.values())))}", file=sys.stderr)
        return 1
    return scaffold(sys.argv[1])


if __name__ == "__main__":
    sys.exit(main())
